services:
  mysql:
    image: mysql:8.0
    container_name: medscan_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: medscan_db
      MYSQL_USER: medscan_user
      MYSQL_PASSWORD: medscan_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: